#! /bin/bash

if [ "$1" != "monitor" ] 
	then
	echo 1
	else
while :;
do
echo "06/16 20:32:48  rcvi addr unit       8 : hu B2  (Family_room_Pot_lights)"
sleep 1
echo "06/16 20:32:48  rcvi func          Off : hc A"
sleep 10
echo "06/16 20:31:49  sndc addr unit      14 : hu A14 (Staircase_Lamp)"
sleep 1
echo "06/16 20:31:49  sndc func           On : hc A"
sleep 10
echo "06/16 20:32:18  rcvi addr unit       5 : hu A5  (Family_room_Pot_lights)"
sleep 1
echo "06/16 20:32:18  rcvi func           On : hc A"
sleep 10
echo "06/16 20:32:48  rcvi addr unit       5 : hu A5  (Family_room_Pot_lights)"
sleep 1
echo "06/16 20:32:48  rcvi func          Off : hc A"
sleep 10
echo "06/16 20:32:48  rcvi addr unit       5 : hu B1  (Family_room_Pot_lights)"
sleep 1
echo "06/16 20:32:48  rcvi func          Off : hc B"
sleep 10
done
fi

